### ISSUE TITLE
Question about@:buildXml()

### ISSUE THREAD

**Issue by Lelelo1** [Gaikov/HaxeWithCppIntegrationExample#1]
I am wondering about the following line:
`@:buildXml('<target id="haxe"><lib name="../../../HaxeCpp/Debug/HaxeCpp.lib"/></target>')`

Can it be removed? Is it the same as the [hxcpp](https://lib.haxe.org/p/hxcpp/) library, and is that not already there by using `--cpp` in `compile.hxml`?

**Comment by Gaikov** [comment]
HaxeCpp is custom cpp library which builds from
https://github.com/Gaikov/HaxeWithCppIntegrationExample/tree/master/HaxeCpp

it is not the same as hxcpp

**Comment by Lelelo1** [comment]
When `haxe build.hxml`, I get:

> clang: error: no such file or directory: '../../../HaxeCpp/Debug/HaxeCpp.lib'
Error: Build failed

I can't find HaxeCpp.lib anywhere in the project before or after building it

Should it be built separately?

**Comment by Lelelo1** [comment]
Since I am on mac I built it with `g++`: https://stackoverflow.com/questions/5947067/how-to-create-a-static-library-with-g
Changed `HaxeCpp.lib` to `HaxeCpp.lib` in the buildXml. Then it compiled. Thanks for the example.

I also got:
> ld: warning: object file (../../../HaxeCpp/Debug/HaxeCpp.a(HaxeCpp.o)) was built for newer macOS version (11.0) than being linked (10.9)

but I probably just have to update something..
